# Site settings
title: 'Deer Hunter' # Your Title
tagline: 'Live 4 nothing or die 4 something' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl:  # the subpath of your site, e.g. /blog/
