# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            思い出
tagline:          'Dear is Deer'
description:      'Dear is Deer'
url:              kangz.me

author:
  name:           '广隶'
  url:            kangz.me

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : 广隶
