# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            思い出
tagline:          'Dear is Deer'
description:      'You may say I''m a dreamer but I''m not the only one.'
url:              http://kangz.me

author:
  name:           '广隶'
  url:            https://Hikang.github.io

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : soohu
